url: http://127.0.0.1:8066

swagger_open: true

dev_fresh: 1

path:
    storage: "/reallove/testdata/storage/"
    log: ""
    pid: ""
    cache: ""


mysql:
    hostname: 127.0.0.1
    username: root
    password: env(DB_PASSWORD)
    timeout: 1
    readtime: 2.3
