url: http://127.0.0.1:8888

swagger_open: true

dev_fresh: 1

path:
    log_folder: "/Users/Ben/work/wangxiao/ggg-frame/log/"
    runtime_folder: "/Users/Ben/work/wangxiao/ggg-frame/runtime/"

mysql:
    hostname: 127.0.0.1
    username: yejianfeng
    password: 123
    timeout: 1
    readtime: 2.3
